# Generated by Django 5.2.6 on 2025-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_portfolio_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.TextField(default='https://example.com/default-image.jpg'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.TextField(default='https://example.com/default-image.jpg'),
        ),
    ]
