# Generated by Django 5.2.6 on 2025-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_hobbies_hobby_image_portfolio_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_paragraph',
            field=models.TextField(default='default paragraph'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_paragraph',
            field=models.TextField(default='default paragraph'),
        ),
    ]
