# Generated by Django 5.2.6 on 2025-09-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0004_hobbies_hobby_paragraph_portfolio_project_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.CharField(default='https://example.com/default-image.jpg', max_length=200),
        ),
    ]
