# Generated by Django 5.2.6 on 2025-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0005_alter_portfolio_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(blank=True, default='https://example.com/default-image.jpg', upload_to=''),
        ),
    ]
