# Generated by Django 5.2.6 on 2025-09-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0006_alter_portfolio_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.TextField(default='https://example.com/default-image.jpg'),
        ),
    ]
